version: '3'

services:
  alerta-web-mom:
    image: alerta/alerta-beta
    ports:
      - 8001:80
    volumes:
      - ./config/config.mom.json:/usr/share/nginx/html/config.json:ro

  alerta-api-mom:
    build: .
    image: alerta-api
    environment:
      DATABASE_URL: postgres://postgres:postgres@mom-db/mom
    depends_on:
      - mom-db
    ports:
      - 8088:8080

  mom-db:
    image: postgres
    volumes:
      - ./pg-data-mom:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  alerta-web-mlm:
    image: alerta/alerta-beta
    ports:
      - 9001:80
    volumes:
      - ./config/config.mlm.json:/usr/share/nginx/html/config.json:ro

  alerta-api-mlm:
    build: .
    image: alerta-api
    environment:
      DATABASE_URL: postgres://postgres:postgres@mlm-db/mlm
    depends_on:
      - mlm-db
    ports:
      - 9080:8080

  mlm-db:
    image: postgres
    volumes:
      - ./pg-data-mlm:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mlm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  alerta-web-elm:
    image: alerta/alerta-beta
    ports:
      - 10001:80
    volumes:
      - ./config/config.elm.json:/usr/share/nginx/html/config.json:ro

  alerta-api-elm:
    build: .
    image: alerta-api
    environment:
      DATABASE_URL: postgres://postgres:postgres@elm-db/elm
    depends_on:
      - elm-db
    ports:
      - 10080:8080

  elm-db:
    image: postgres
    volumes:
      - ./pg-data-elm:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: elm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
